/*written by : Mina Nashaat */

#ifndef DIO_conf.h
#define DIO_conf.h

#define DIR_PORTA_PIN0 OUTPUT
#define DIR_PORTA_PIN1 OUTPUT
#define DIR_PORTA_PIN2 OUTPUT
#define DIR_PORTA_PIN3 OUTPUT
#define DIR_PORTA_PIN4 OUTPUT
#define DIR_PORTA_PIN5 OUTPUT
#define DIR_PORTA_PIN6 OUTPUT
#define DIR_PORTA_PIN7 OUTPUT

#define DIR_PORTB_PIN0 OUTPUT
#define DIR_PORTB_PIN1 OUTPUT
#define DIR_PORTB_PIN2 OUTPUT
#define DIR_PORTB_PIN3 OUTPUT
#define DIR_PORTB_PIN4 OUTPUT
#define DIR_PORTB_PIN5 OUTPUT
#define DIR_PORTB_PIN6 OUTPUT
#define DIR_PORTB_PIN7 OUTPUT

#define DIR_PORTC_PIN0 OUTPUT
#define DIR_PORTC_PIN1 OUTPUT
#define DIR_PORTC_PIN2 OUTPUT
#define DIR_PORTC_PIN3 OUTPUT
#define DIR_PORTC_PIN4 OUTPUT
#define DIR_PORTC_PIN5 OUTPUT
#define DIR_PORTC_PIN6 OUTPUT
#define DIR_PORTC_PIN7 OUTPUT

#define DIR_PORTD_PIN0 OUTPUT
#define DIR_PORTD_PIN1 OUTPUT
#define DIR_PORTD_PIN2 OUTPUT
#define DIR_PORTD_PIN3 OUTPUT
#define DIR_PORTD_PIN4 OUTPUT
#define DIR_PORTD_PIN5 OUTPUT
#define DIR_PORTD_PIN6 OUTPUT
#define DIR_PORTD_PIN7 OUTPUT

#define val_PORTA_PIN0 HIGH
#define val_PORTA_PIN1 LOW
#define val_PORTA_PIN2 LOW
#define val_PORTA_PIN3 LOW
#define val_PORTA_PIN4 LOW
#define val_PORTA_PIN5 LOW
#define val_PORTA_PIN6 LOW
#define val_PORTA_PIN7 LOW

#define val_PORTB_PIN0 LOW
#define val_PORTB_PIN1 LOW
#define val_PORTB_PIN2 LOW
#define val_PORTB_PIN3 LOW
#define val_PORTB_PIN4 LOW
#define val_PORTB_PIN5 LOW
#define val_PORTB_PIN6 LOW
#define val_PORTB_PIN7 LOW

#define val_PORTC_PIN0 LOW
#define val_PORTC_PIN1 LOW
#define val_PORTC_PIN2 LOW
#define val_PORTC_PIN3 LOW
#define val_PORTC_PIN4 LOW
#define val_PORTC_PIN5 LOW
#define val_PORTC_PIN6 LOW
#define val_PORTC_PIN7 LOW

#define val_PORTD_PIN0 LOW
#define val_PORTD_PIN1 LOW
#define val_PORTD_PIN2 LOW
#define val_PORTD_PIN3 LOW
#define val_PORTD_PIN4 LOW
#define val_PORTD_PIN5 LOW
#define val_PORTD_PIN6 LOW
#define val_PORTD_PIN7 LOW
 
#endif
